name: Build LaTeX document
on: [push]

permissions:
  contents: write

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@master
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: crichard.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@master
        with:
          name: CesarRichard_CV
          path: crichard.pdf
      - name: Create Release
        id: create_release
        uses: actions/create-release@master
        with:
          tag_name: v1.1.0  # Change this to the version you want
          release_name: Release v1.1.0
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: crichard.pdf
          asset_name: CesarRichard_CV.pdf
          tag: v1.1.0  # Use the same tag as in 'Create Release'
          overwrite: true
          body: "=)"
